name: ci
on: [push, pull_request]
env:
  HUSKY: 0
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn test
